name: vm_fm_4
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # local database
  shared_preferences: ^2.2.0
  shared_preferences_foundation: ^2.2.2

  # dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.2

  # provider --state management
  provider: ^6.0.5

  # network --service management
  dio: ^5.2.1+1
  dartz: ^0.10.1

  # route management
  auto_route: ^7.7.0

  # json management
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  # log management
  logger: ^1.4.0

  # persistent tab bar --for bottom navigation bar
  bottom_navy_bar: ^6.0.0

  # animated widgets
  animated_widgets: ^1.1.0

  # localizations
  easy_localization: ^3.0.2

  # firebase --for push notification
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.7

  # device info --get device info
  device_info_plus: ^9.0.2

  # snackbar
  top_snackbar_flutter: ^3.1.0


  cupertino_icons: ^1.0.2
  rounded_loading_button: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for auto router
  auto_route_generator: ^7.2.0

  # for auto router, code generation
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
